name: CI - Validate and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Vérification HTML
      - name: Validate HTML
        uses: Cyb3r-Jak3/html5validator-action@v0.4.3

      # Vérification CSS avec Stylelint
      - name: Install Stylelint
        run: npm install stylelint stylelint-config-standard

      - name: Run Stylelint
        run: npx stylelint "**/*.css"

      # Vérification JS avec ESLint
      - name: Install ESLint
        run: npm install eslint

      - name: Run ESLint
        run: npx eslint "**/*.js"
